package sankey

import (
	"math"
	"testing"
)

// sampleGraph is a small DAG: A,B → C; A → D; C,D → E.
func sampleGraph() *Graph {
	return &Graph{
		Nodes: []*Node{{ID: "A"}, {ID: "B"}, {ID: "C"}, {ID: "D"}, {ID: "E"}},
		Links: []*Link{
			{SourceID: "A", TargetID: "C", Value: 5},
			{SourceID: "B", TargetID: "C", Value: 3},
			{SourceID: "A", TargetID: "D", Value: 2},
			{SourceID: "C", TargetID: "E", Value: 6},
			{SourceID: "D", TargetID: "E", Value: 2},
		},
	}
}

func nodeByID(g *Graph, id string) *Node {
	for _, n := range g.Nodes {
		if n.ID == id {
			return n
		}
	}
	return nil
}

// wantNode is a d3-sankey reference row (see internal/d3/sankey test notes):
// generated by running d3-sankey@0.12 with nodeAlign(sankeyCenter),
// nodeWidth(12), nodePadding(12), size([600,400]) over sampleGraph.
type wantNode struct {
	id                   string
	depth, height, layer int
	value                float64
	x0, x1, y0, y1       float64
}

type wantLink struct {
	s, t      string
	y0, y1, w float64
}

func closeTo(a, b float64) bool { return math.Abs(a-b) < 1e-4 }

// TestLayout_MatchesD3 validates the port against real d3-sankey output.
func TestLayout_MatchesD3(t *testing.T) {
	g := sampleGraph()
	New().NodeAlign(SankeyCenter).NodeWidth(12).NodePadding(12).Size(600, 400).Layout(g)

	wantNodes := []wantNode{
		{"A", 0, 2, 0, 7, 0, 12, 0, 271.6},
		{"B", 0, 2, 0, 3, 0, 12, 283.6, 400},
		{"C", 1, 1, 1, 8, 294, 306, 0, 310.4},
		{"D", 1, 1, 1, 2, 294, 306, 322.4, 400},
		{"E", 2, 0, 2, 8, 588, 600, 21.267843, 331.667843},
	}
	for _, w := range wantNodes {
		n := nodeByID(g, w.id)
		if n.Depth != w.depth || n.Height != w.height || n.Layer != w.layer {
			t.Errorf("%s: depth/height/layer = %d/%d/%d, want %d/%d/%d",
				w.id, n.Depth, n.Height, n.Layer, w.depth, w.height, w.layer)
		}
		if !closeTo(n.Value, w.value) {
			t.Errorf("%s: value = %v, want %v", w.id, n.Value, w.value)
		}
		if !closeTo(n.X0, w.x0) || !closeTo(n.X1, w.x1) || !closeTo(n.Y0, w.y0) || !closeTo(n.Y1, w.y1) {
			t.Errorf("%s: rect = (%v,%v,%v,%v), want (%v,%v,%v,%v)",
				w.id, n.X0, n.Y0, n.X1, n.Y1, w.x0, w.y0, w.x1, w.y1)
		}
	}

	wantLinks := []wantLink{
		{"A", "C", 97, 97, 194},
		{"B", "C", 341.8, 252.2, 116.4},
		{"A", "D", 232.8, 361.2, 77.6},
		{"C", "E", 116.4, 137.667843, 232.8},
		{"D", "E", 361.2, 292.867843, 77.6},
	}
	for _, w := range wantLinks {
		l := linkByEnds(g, w.s, w.t)
		if l == nil {
			t.Fatalf("missing link %s->%s", w.s, w.t)
		}
		if !closeTo(l.Y0, w.y0) || !closeTo(l.Y1, w.y1) || !closeTo(l.Width, w.w) {
			t.Errorf("%s->%s: y0/y1/width = %v/%v/%v, want %v/%v/%v",
				w.s, w.t, l.Y0, l.Y1, l.Width, w.y0, w.y1, w.w)
		}
	}
}

func linkByEnds(g *Graph, s, t string) *Link {
	for _, l := range g.Links {
		if l.Source.ID == s && l.Target.ID == t {
			return l
		}
	}
	return nil
}

// TestLayout_Deterministic ensures the layout is a pure function of its input.
func TestLayout_Deterministic(t *testing.T) {
	g1, g2 := sampleGraph(), sampleGraph()
	New().NodeAlign(SankeyCenter).NodeWidth(12).NodePadding(12).Size(600, 400).Layout(g1)
	New().NodeAlign(SankeyCenter).NodeWidth(12).NodePadding(12).Size(600, 400).Layout(g2)
	for i := range g1.Nodes {
		if g1.Nodes[i].Y0 != g2.Nodes[i].Y0 || g1.Nodes[i].X0 != g2.Nodes[i].X0 {
			t.Fatalf("node %d not deterministic", i)
		}
	}
}

// TestLayout_Invariants checks structural properties that must always hold.
func TestLayout_Invariants(t *testing.T) {
	g := sampleGraph()
	New().NodeAlign(SankeyJustify).Size(600, 400).Layout(g)

	for _, n := range g.Nodes {
		if n.X0 < 0 || n.X1 > 600 || n.Y0 < -1e-6 || n.Y1 > 400+1e-6 {
			t.Errorf("node %s escapes extent: (%v,%v,%v,%v)", n.ID, n.X0, n.Y0, n.X1, n.Y1)
		}
		if n.Y1 < n.Y0 {
			t.Errorf("node %s inverted: y0=%v y1=%v", n.ID, n.Y0, n.Y1)
		}
	}
	// Flow conservation: a node's height (span) equals the summed width of its
	// larger side (all links share one ky, so span == value*ky == sum widths).
	for _, n := range g.Nodes {
		span := n.Y1 - n.Y0
		out := sumWidth(n.SourceLinks)
		in := sumWidth(n.TargetLinks)
		bigger := math.Max(out, in)
		if bigger > 0 && !closeTo(span, bigger) {
			t.Errorf("node %s span %v != max(in=%v,out=%v)", n.ID, span, in, out)
		}
	}
}

func sumWidth(links []*Link) float64 {
	total := 0.0
	for _, l := range links {
		total += l.Width
	}
	return total
}

// TestAlign_Right pushes sinks to the right edge; TestAlign functions differ
// only when the DAG has ambiguous depths, but Right must always place a sink
// (height 0) in the last column.
func TestAlign_Right(t *testing.T) {
	g := sampleGraph()
	New().NodeAlign(SankeyRight).Size(600, 400).Layout(g)
	e := nodeByID(g, "E")
	if e.Layer != 2 {
		t.Errorf("sink E layer = %d, want 2 (right-aligned)", e.Layer)
	}
}

// TestFixedValue overrides a node's flow-derived value.
func TestFixedValue(t *testing.T) {
	g := sampleGraph()
	fv := 100.0
	nodeByID(g, "A").FixedValue = &fv
	New().Size(600, 400).Layout(g)
	if nodeByID(g, "A").Value != 100 {
		t.Errorf("fixed value ignored: got %v", nodeByID(g, "A").Value)
	}
}
