package grid

import "slices"

// PerpendicularPolygon is a polygon defined by split left/right vertex lists,
// so a path can be generated by traversing the right vertices (y ascending)
// then the left vertices (y descending) — a clockwise traversal. The polygon
// is not closed; the first vertex is the first right vertex and the last is
// the last left vertex (close it with, e.g., a linearClosed curve).
//
// Mirrors @nivo/grid perpendicularPolygon.
type PerpendicularPolygon struct {
	left  []Vertex
	right []Vertex
}

// NewPerpendicularPolygon builds an empty perpendicular polygon.
func NewPerpendicularPolygon() *PerpendicularPolygon {
	return &PerpendicularPolygon{}
}

// AddRight appends vertices to the right side (sorted by y ascending).
func (p *PerpendicularPolygon) AddRight(vertices ...Vertex) {
	p.right = append(p.right, vertices...)
}

// AddLeft prepends vertices to the left side (so the left list ends up sorted
// by y descending).
func (p *PerpendicularPolygon) AddLeft(vertices ...Vertex) {
	// unshift: prepend in order so the first given vertex becomes the new head.
	p.left = append(append([]Vertex{}, vertices...), p.left...)
}

// Vertices returns the polygon's vertices in traversal order (right then left).
func (p *PerpendicularPolygon) Vertices() []Vertex {
	out := make([]Vertex, 0, len(p.right)+len(p.left))
	out = append(out, p.right...)
	out = append(out, p.left...)
	return out
}

// Debug returns the raw left/right lists for inspection.
func (p *PerpendicularPolygon) Debug() (left, right []Vertex) {
	return p.left, p.right
}

// GetCellsPolygons merges a list of cells (already laid out in a grid) into
// the minimal set of perpendicular polygons by grouping adjacent rows that
// touch and share left/right edges. Used by heatmap/waffle to draw a single
// outline per contiguous block instead of per-cell rects.
//
// Mirrors @nivo/grid getCellsPolygons.
func GetCellsPolygons[C GridCellLike](cells []C) [][]Vertex {
	// 1. Sort cells by y then x.
	sorted := make([]C, len(cells))
	copy(sorted, cells)
	slices.SortFunc(sorted, func(a, b C) int {
		if a.GetY() != b.GetY() {
			if a.GetY() < b.GetY() {
				return -1
			}
			return 1
		}
		if a.GetX() < b.GetX() {
			return -1
		}
		if a.GetX() > b.GetX() {
			return 1
		}
		return 0
	})

	// 2. Compute a bounding box for each row of cells.
	type rowBox = BoundingBox
	var rows []rowBox
	var current *rowBox
	for _, cell := range sorted {
		if current == nil || cell.GetY() != current.Top {
			box := rowBox{
				Top:    cell.GetY(),
				Right:  cell.GetX() + cell.GetWidth(),
				Bottom: cell.GetY() + cell.GetHeight(),
				Left:   cell.GetX(),
			}
			rows = append(rows, box)
			current = &rows[len(rows)-1]
		} else {
			current.Right = cell.GetX() + cell.GetWidth()
		}
	}

	// 3. Compute polygons for each group of adjacent rows.
	var polygons []*PerpendicularPolygon
	var currentPolygon *PerpendicularPolygon
	for index, row := range rows {
		var previous *rowBox
		if index > 0 {
			previous = &rows[index-1]
		}
		if previous == nil || !AreBoundingBoxTouching(row, *previous) {
			currentPolygon = NewPerpendicularPolygon()
			currentPolygon.AddLeft(Vertex{row.Left, row.Top})
			currentPolygon.AddRight(Vertex{row.Right, row.Top})
			polygons = append(polygons, currentPolygon)
		}
		if previous != nil && row.Left != previous.Left {
			currentPolygon.AddLeft(Vertex{row.Left, row.Top})
		}
		if previous != nil && row.Right != previous.Right {
			currentPolygon.AddRight(Vertex{row.Right, row.Top})
		}
		currentPolygon.AddLeft(Vertex{row.Left, row.Bottom})
		currentPolygon.AddRight(Vertex{row.Right, row.Bottom})
	}

	out := make([][]Vertex, len(polygons))
	for i, p := range polygons {
		out[i] = p.Vertices()
	}
	return out
}

// GridCellLike is the minimal cell interface GetCellsPolygons needs; GridCell
// satisfies it. The generic keeps the helper usable for extended cell types.
type GridCellLike interface {
	GetX() float64
	GetY() float64
	GetWidth() float64
	GetHeight() float64
}

// GetX/Y/GetWidth/GetHeight let GridCell satisfy GridCellLike.
func (c GridCell) GetX() float64      { return c.X }
func (c GridCell) GetY() float64      { return c.Y }
func (c GridCell) GetWidth() float64  { return c.Width }
func (c GridCell) GetHeight() float64 { return c.Height }
