// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package bar

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import "github.com/geoffjay/templ-charts/charts/legends"

// BarLegendsProps is the input to the BarLegends templ component.
type BarLegendsProps struct {
	Width   float64
	Height  float64
	Legends []LegendWithData
}

// BarLegends renders each legend box via legends.BoxLegendSvg. Mirrors
// @nivo/bar BarLegends. Series toggle (hx-post) is wired through the
// LegendProps.Toggle/ChartID fields set by UseBar.
func BarLegends(props BarLegendsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		for _, lw := range props.Legends {
			lp := lw.Props.LegendProps
			items := legendItems(lw.Data)
			templ_7745c5c3_Err = legends.BoxLegendSvg(legends.BoxLegendSvgProps{
				Props: legends.LegendProps{
					Anchor:            lp.Anchor,
					Direction:         lp.Direction,
					Items:             items,
					TranslateX:        lp.TranslateX,
					TranslateY:        lp.TranslateY,
					ItemDirection:     lp.ItemDirection,
					ItemWidth:         lp.ItemWidth,
					ItemHeight:        lp.ItemHeight,
					ItemOpacity:       lp.ItemOpacity,
					SymbolShape:       lp.SymbolShape,
					SymbolSize:        lp.SymbolSize,
					SymbolSpacing:     lp.SymbolSpacing,
					SymbolBorderColor: lp.SymbolBorderColor,
					SymbolBorderWidth: lp.SymbolBorderWidth,
					Toggle:            lp.Toggle,
					ChartID:           lp.ChartID,
				},
				ChartWidth:  props.Width,
				ChartHeight: props.Height,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
