// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
	"github.com/geoffjay/templ-charts/charts/htmx"
)

// DashboardKPICard is one KPI tile at the top of the dashboard page.
type DashboardKPICard struct {
	Label   string
	Value   string
	Delta   string
	DeltaUp bool
	SVG     string
}

// DashboardPageProps is the input to the DashboardPage: pre-rendered SVGs for
// every panel plus the htmx instance ids of the interactive charts.
type DashboardPageProps struct {
	KPIs      []DashboardKPICard
	MainID    string
	MainSVG   string
	DonutID   string
	DonutSVG  string
	BarID     string
	BarSVG    string
	BulletSVG string
}

// dashCSS is the dashboard page's scoped styling: a dark shell with card
// panels, laid out with CSS grid. Scoped under .dash so the rest of the demo
// app keeps its light styling.
const dashCSS = `
.dash { background:#0f172a; margin:-24px; padding:24px; border-radius:0; }
.dash, .dash * { box-sizing:border-box; }
.dash-grid { max-width:1400px; margin:0 auto; display:grid; gap:16px; }
.dash-title { color:#e2e8f0; font-size:18px; font-weight:600; margin:0; }
.dash-sub { color:#64748b; font-size:13px; margin:2px 0 8px; }
.dash-card { background:#1e293b; border:1px solid #334155; border-radius:12px; padding:16px; }
.dash-card h3 { margin:0 0 2px; font-size:14px; font-weight:600; color:#e2e8f0; }
.dash-card .hint { margin:0 0 10px; font-size:12px; color:#64748b; }
.dash-kpis { display:grid; grid-template-columns:repeat(auto-fit,minmax(230px,1fr)); gap:16px; }
.dash-kpi .label { font-size:12px; color:#94a3b8; margin:0; }
.dash-kpi .row { display:flex; align-items:baseline; justify-content:space-between; margin:2px 0 10px; }
.dash-kpi .value { font-size:26px; font-weight:700; color:#f1f5f9; }
.dash-kpi .delta { font-size:12px; font-weight:600; }
.dash-kpi .delta.up { color:#34d399; }
.dash-kpi .delta.down { color:#f87171; }
.dash-main { display:grid; grid-template-columns:2fr 1fr; gap:16px; }
.dash-side { display:grid; grid-template-rows:1fr 1fr; gap:16px; }
@media (max-width: 1000px) { .dash-main { grid-template-columns:1fr; } }
.dash .chart svg { width:100%; height:auto; display:block; }
.dash .tc-chart-tooltip { background:rgba(15,23,42,0.95); border-color:#334155; color:#e2e8f0; }
`

// DashboardPage renders the /dashboard page: a dark, composed, real-world
// layout — KPI sparkline cards, a large interactive trend chart, a donut +
// stacked-bar side column, and a goal-tracking bullet row.
func DashboardPage(props DashboardPageProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw("<style>"+dashCSS+"</style>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"dash\"><div class=\"dash-grid\"><div><p class=\"dash-title\">Revenue overview</p><p class=\"dash-sub\">Every panel is a templ-charts component (or a hand-composed Use* hook) sharing one dark theme and palette. Hover the trend, donut, bars, and bullets.</p></div><div class=\"dash-kpis\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, k := range props.KPIs {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"dash-card dash-kpi\"><p class=\"label\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(k.Label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/app/templates/dashboard.templ`, Line: 67, Col: 32}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p><div class=\"row\"><span class=\"value\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(k.Value)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/app/templates/dashboard.templ`, Line: 69, Col: 36}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if k.DeltaUp {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<span class=\"delta up\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(k.Delta)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/app/templates/dashboard.templ`, Line: 71, Col: 40}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<span class=\"delta down\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(k.Delta)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/app/templates/dashboard.templ`, Line: 73, Col: 42}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(k.SVG).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div><div class=\"dash-main\"><div class=\"dash-card\"><h3>Monthly recurring revenue</h3><p class=\"hint\">by segment, $k — hover for the nearest point (client-side mesh)</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = htmx.Mount(htmx.MountProps{ID: props.MainID, SVG: props.MainSVG, Interactive: true, Class: "chart"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div><div class=\"dash-side\"><div class=\"dash-card\"><h3>Revenue share</h3><p class=\"hint\">this quarter — hover an arc</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = htmx.Mount(htmx.MountProps{ID: props.DonutID, SVG: props.DonutSVG, Interactive: true, Class: "chart"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div><div class=\"dash-card\"><h3>Weekly revenue</h3><p class=\"hint\">last six weeks, stacked</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = htmx.Mount(htmx.MountProps{ID: props.BarID, SVG: props.BarSVG, Interactive: true, Class: "chart"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div></div></div><div class=\"dash-card\"><h3>Quarterly goals</h3><p class=\"hint\">measure vs. target (marker), qualitative ranges behind</p><div class=\"chart\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(props.BulletSVG).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
