// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package line

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import "fmt"

// MeshProps is the input to the Mesh templ component. v1 simplifies nivo's
// voronoi-based mesh to a single transparent <rect> overlay that captures
// mouse position via HTMX; the server-side handler resolves the nearest point
// and returns the tooltip + crosshair. When Debug is true, the overlay gets a
// red stroke so the mesh bounds are visible.
type MeshProps struct {
	Width   float64
	Height  float64
	Debug   bool
	ChartID string
	// DataMesh, when non-empty, is a JSON array of {x,y,html} points the client
	// interactivity layer (charts/interact) uses for nearest-point hover +
	// crosshair. When set, the htmx mesh round-trip is suppressed.
	DataMesh string
}

// Mesh renders a transparent overlay <rect> for hover capture. Mirrors
// @nivo/line Mesh (voronoi-based in nivo; simplified to a single overlay in v1).
//
// hx-vals converts the cursor's screen position into the rect's local SVG user
// coordinates via the rect's screen CTM. Because the rect lives inside the
// margin-translated <g> and shares the chart's coordinate system, the result is
// already in inner-chart units (0..innerWidth/Height) — matching the computed
// point coordinates the server compares against. Using getScreenCTM (rather
// than event.offsetX/offsetY) is correct under viewBox scaling and avoids the
// cross-browser inconsistencies of offsetX/offsetY on SVG elements.
func Mesh(props MeshProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<rect x=\"0\" y=\"0\" width=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmtL(props.Width))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `charts/line/mesh.templ`, Line: 35, Col: 27}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" height=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmtL(props.Height))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `charts/line/mesh.templ`, Line: 36, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" fill=\"black\" fill-opacity=\"0\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Debug {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " stroke=\"red\" stroke-width=\"1\" stroke-opacity=\"0.5\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.DataMesh != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " data-tc-mesh=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(props.DataMesh)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `charts/line/mesh.templ`, Line: 45, Col: 32}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " else")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.ChartID != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " hx-get=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("/charts/%s/hover?mesh=1", props.ChartID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `charts/line/mesh.templ`, Line: 47, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" hx-trigger=\"mouseenter, mousemove throttle:40ms\" hx-swap=\"innerHTML\" hx-target=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("#tooltip-%s", props.ChartID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `charts/line/mesh.templ`, Line: 50, Col: 56}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" hx-vals=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(meshHoverVals)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `charts/line/mesh.templ`, Line: 51, Col: 26}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "></rect>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// meshHoverVals is the htmx hx-vals JS expression that resolves the cursor's
// position in the mesh rect's local SVG user coordinates (inner-chart units).
// It maps the screen point through the rect's inverse screen CTM, which is
// correct under viewBox scaling; it falls back to offsetX/offsetY when the CTM
// is unavailable. The point is cached on event._tcPt so the y expression
// reuses the x expression's computation.
const meshHoverVals = "js:{" +
	"x: (event._tcPt = (function(e){" +
	"var r=e.target,s=r.ownerSVGElement,m=r.getScreenCTM&&r.getScreenCTM();" +
	"if(!s||!m){return {x:e.offsetX,y:e.offsetY};}" +
	"var p=s.createSVGPoint();p.x=e.clientX;p.y=e.clientY;" +
	"return p.matrixTransform(m.inverse());" +
	"})(event), Math.round(event._tcPt.x)), " +
	"y: Math.round(event._tcPt.y)}"

var _ = templruntime.GeneratedTemplate
