// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package radialbar

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import "github.com/geoffjay/templ-charts/charts/core"

// RadialBar renders a complete radial-bar SVG: dimensions → UseRadialBar →
// layer pipeline (grid → tracks → bars → labels → legends) → SvgWrapper.
// Mirrors @nivo/radial-bar RadialBar. Static render (the interactive hover
// tooltip arrives with the charts/interact client layer).
func RadialBar(props RadialBarProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		props = applyDefaults(props)
		dims := core.UseDimensions(props.Width, props.Height, props.Margin)
		props.Width = dims.InnerWidth
		props.Height = dims.InnerHeight
		result := UseRadialBar(props)
		theme := resolveTheme(props.Theme)
		templ_7745c5c3_Err = core.SvgWrapper(core.SvgWrapperProps{
			Width:           dims.OuterWidth,
			Height:          dims.OuterHeight,
			Margin:          dims.Margin,
			Background:      themeBackground(theme),
			Role:            props.Role,
			AriaLabel:       props.AriaLabel,
			AriaLabelledBy:  props.AriaLabelledBy,
			AriaDescribedBy: props.AriaDescribedBy,
			Title:           props.Title,
			Desc:            props.Desc,
			IsFocusable:     props.IsFocusable,
			Responsive:      props.Responsive,
		}, renderLayers(props, result, theme)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
