// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package pie

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"fmt"

	"github.com/geoffjay/templ-charts/charts/arcs"
)

// ArcsProps is the input to the Arcs templ component. Mirrors @nivo/pie Arcs
// (SVG subset; interactive handlers routed through HTMX).
type ArcsProps struct {
	CenterX, CenterY float64
	Data             []ComputedDatum
	ArcGenerator     *arcs.ArcGenerator
	BorderWidth      float64
	BorderColor      func(ComputedDatum) string
	Interactive      bool
	ChartID          string
	Animate          bool
	TransitionMode   TransitionMode
}

// Arcs renders the arcs layer: a <g translate(center)> with one <path> per
// arc. Mirrors @nivo/pie Arcs (delegates to arcs.ArcsLayer).
func Arcs(props ArcsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		items := buildArcLayerItems(props)
		templ_7745c5c3_Err = arcs.ArcsLayer(arcs.ArcsLayerProps{
			Items:   items,
			CenterX: props.CenterX,
			CenterY: props.CenterY,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// buildArcLayerItems converts pie.ComputedDatum slice to arcs.ArcLayerItem
// slice, generating the SVG path for each arc and resolving border color.
func buildArcLayerItems(props ArcsProps) []arcs.ArcLayerItem {
	items := make([]arcs.ArcLayerItem, len(props.Data))
	for i, d := range props.Data {
		path := props.ArcGenerator.GenerateSvgArc(d.Arc.Arc)
		var animateFrom string
		if props.Animate && props.TransitionMode == TransitionModeInnerRadius {
			fromArc := d.Arc.Arc
			fromArc.OuterRadius = d.Arc.InnerRadius
			animateFrom = props.ArcGenerator.GenerateSvgArc(fromArc)
		}
		fill := d.Color
		if d.Fill != "" {
			fill = d.Fill
		}
		stroke := ""
		if props.BorderWidth > 0 && props.BorderColor != nil {
			stroke = props.BorderColor(d)
		}
		var htmxGet, htmxTrigger, htmxSwap, htmxTarget string
		if props.Interactive && props.ChartID != "" {
			htmxGet = fmt.Sprintf("/charts/%s/hover?arc=%s", props.ChartID, d.ID)
			htmxTrigger = "mouseenter"
			htmxSwap = "innerHTML"
			htmxTarget = fmt.Sprintf("#tooltip-%s", props.ChartID)
		}
		items[i] = arcs.ArcLayerItem{
			Arc: d.Arc.Arc,
			Props: arcs.ArcShapeProps{
				Path:            path,
				Fill:            fill,
				Stroke:          stroke,
				StrokeWidth:     props.BorderWidth,
				HxGet:           htmxGet,
				HxTrigger:       htmxTrigger,
				HxSwap:          htmxSwap,
				HxTarget:        htmxTarget,
				Animate:         props.Animate,
				AnimateFromPath: animateFrom,
			},
		}
	}
	return items
}

// --- Arc link labels ---

// ArcLinkLabelsProps is the input to the ArcLinkLabels templ component.
type ArcLinkLabelsProps struct {
	CenterX, CenterY float64
	Data             []ComputedDatum
	GetLabel         func(ComputedDatum) string
	SkipAngle        float64
	Offset           float64
	DiagonalLength   float64
	StraightLength   float64
	Thickness        float64
	TextOffset       float64
	TextColor        string
	LinkColor        string
	FontSize         float64
	FontFamily       string
}

// ArcLinkLabels renders the arc-link-labels layer. Mirrors @nivo/arcs
// ArcLinkLabelsLayer (delegates to arcs.ArcLinkLabelsLayer).
func ArcLinkLabels(props ArcLinkLabelsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		items := buildArcLinkLabelItems(props)
		templ_7745c5c3_Err = arcs.ArcLinkLabelsLayer(arcs.ArcLinkLabelsLayerProps{
			Items:   items,
			CenterX: props.CenterX,
			CenterY: props.CenterY,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func buildArcLinkLabelItems(props ArcLinkLabelsProps) []arcs.ArcLinkLabelItem {
	filtered := filterBySkipAngle(props.Data, props.SkipAngle)
	items := make([]arcs.ArcLinkLabelItem, 0, len(filtered))
	for _, d := range filtered {
		link := arcs.ComputeArcLink(d.Arc.Arc, props.Offset, props.DiagonalLength, props.StraightLength)
		items = append(items, arcs.ArcLinkLabelItem{
			Props: arcs.ArcLinkLabelProps{
				Link:       link,
				Label:      props.GetLabel(d),
				Thickness:  props.Thickness,
				Color:      props.LinkColor,
				TextOffset: props.TextOffset,
				Fill:       props.TextColor,
				FontSize:   props.FontSize,
				FontFamily: props.FontFamily,
			},
		})
	}
	return items
}

// --- Arc labels ---

// ArcLabelsProps is the input to the ArcLabels templ component.
type ArcLabelsProps struct {
	CenterX, CenterY float64
	Data             []ComputedDatum
	GetLabel         func(ComputedDatum) string
	RadiusOffset     float64
	SkipAngle        float64
	SkipRadius       float64
	TextColor        string
	FontSize         float64
	FontFamily       string
}

// ArcLabels renders the arc-labels layer. Mirrors @nivo/arcs ArcLabelsLayer.
func ArcLabels(props ArcLabelsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		items := buildArcLabelItems(props)
		templ_7745c5c3_Err = arcs.ArcLabelsLayer(arcs.ArcLabelsLayerProps{
			Items:   items,
			CenterX: props.CenterX,
			CenterY: props.CenterY,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func buildArcLabelItems(props ArcLabelsProps) []arcs.ArcLabelItem {
	filtered := filterBySkipAngle(props.Data, props.SkipAngle)
	items := make([]arcs.ArcLabelItem, 0, len(filtered))
	for _, d := range filtered {
		if props.SkipRadius > 0 && d.Arc.Thickness < props.SkipRadius {
			continue
		}
		cx, cy := arcs.ComputeArcCenter(d.Arc.Arc, props.RadiusOffset)
		items = append(items, arcs.ArcLabelItem{
			Props: arcs.ArcLabelProps{
				X:          cx,
				Y:          cy,
				Label:      props.GetLabel(d),
				Fill:       props.TextColor,
				FontSize:   props.FontSize,
				FontFamily: props.FontFamily,
			},
		})
	}
	return items
}

// filterBySkipAngle filters pie ComputedDatum by arc angular span (degrees).
func filterBySkipAngle(data []ComputedDatum, skipAngle float64) []ComputedDatum {
	if skipAngle <= 0 {
		return data
	}
	out := make([]ComputedDatum, 0, len(data))
	for _, d := range data {
		if d.Arc.AngleDeg >= skipAngle {
			out = append(out, d)
		}
	}
	return out
}

// computedDatumWithArc adapts pie.ComputedDatum to arcs.DatumWithArc.
type computedDatumWithArc struct{ datum ComputedDatum }

func (c computedDatumWithArc) GetArc() arcs.Arc { return c.datum.Arc.Arc }

// toDatumWithArcSlice converts []ComputedDatum to []arcs.DatumWithArc.
func toDatumWithArcSlice(data []ComputedDatum) []arcs.DatumWithArc {
	out := make([]arcs.DatumWithArc, len(data))
	for i, d := range data {
		out[i] = computedDatumWithArc{datum: d}
	}
	return out
}

var _ = templruntime.GeneratedTemplate
