// log.go — port of d3-scale's scaleLog.
//
// A log scale is a continuous scale where the domain is transformed via log
// before the linear domain→range mapping:
//
//	t = (log(x) - log(d0)) / (log(d1) - log(d0))
//	r = r0 + (r1 - r0) * t
//
// d3 supports a configurable base (default 10) and reflects the transform for
// negative domains. Ticks are generated by walking powers of the base and
// multiples 1..base-1 within each decade. Nice floors to the nearest power.
package d3scale

import "math"

// Log is a continuous logarithmic scale.
type Log struct {
	domain        [2]float64
	rangeVals     [2]float64
	base          float64
	clamp         bool
	round         bool
	interpolateFn func(float64) float64
	// logs/pows are chosen based on base and domain sign
	logs func(float64) float64
	pows func(float64) float64
	// negative domain flips the transforms
	negative bool
}

// NewLog constructs a log scale with base 10, domain [1, 10], range [0, 1].
func NewLog() *Log {
	l := &Log{
		domain:    [2]float64{1, 10},
		rangeVals: [2]float64{0, 1},
		base:      10,
	}
	l.rescale()
	return l
}

// Type returns "log".
func (l *Log) Type() string { return "log" }

// Base returns the log base.
func (l *Log) Base() float64 { return l.base }

// SetBase sets the log base and rescales.
func (l *Log) SetBase(b float64) *Log {
	l.base = b
	l.rescale()
	return l
}

// Domain returns the domain.
func (l *Log) Domain() [2]float64 { return l.domain }

// SetDomain sets the domain. Both endpoints must be strictly positive or
// strictly negative (d3 throws otherwise).
func (l *Log) SetDomain(d0, d1 float64) *Log {
	l.domain = [2]float64{d0, d1}
	l.rescale()
	return l
}

// Range returns the range.
func (l *Log) Range() [2]float64 { return l.rangeVals }

// SetRange sets the range.
func (l *Log) SetRange(r0, r1 float64) *Log {
	l.rangeVals = [2]float64{r0, r1}
	l.round = false
	l.rebuildInterpolator()
	return l
}

// SetRangeRound sets the range with rounding.
func (l *Log) SetRangeRound(r0, r1 float64) *Log {
	l.rangeVals = [2]float64{r0, r1}
	l.round = true
	l.rebuildInterpolator()
	return l
}

// Clamp reports clamping state.
func (l *Log) Clamp() bool { return l.clamp }

// SetClamp enables/disables clamping.
func (l *Log) SetClamp(c bool) *Log {
	l.clamp = c
	return l
}

// Call maps a domain value to a range value.
func (l *Log) Call(x float64) float64 {
	// d3: transform(clamp(x)) then piecewise. For our 2-element domain this is
	// deinterpolate over transformed domain, then interpolate range.
	xc := x
	if l.clamp {
		xc = clampLogDomain(x, l.domain)
	}
	dx := l.logs(xc)
	t := deinterpolate(l.logs(l.domain[0]), l.logs(l.domain[1]))(dx)
	if l.clamp {
		t = clamp01(t)
	} else if math.IsNaN(t) {
		return t
	}
	return l.interpolateFn(t)
}

// Invert maps a range value back to a domain value.
func (l *Log) Invert(y float64) float64 {
	r0, r1 := l.rangeVals[0], l.rangeVals[1]
	rd := r1 - r0
	if rd == 0 {
		return l.domain[0]
	}
	t := (y - r0) / rd
	if l.clamp {
		t = clamp01(t)
	}
	// x = pows(log(d0) + t * (log(d1) - log(d0)))
	ld0 := l.logs(l.domain[0])
	ld1 := l.logs(l.domain[1])
	return l.pows(ld0 + t*(ld1-ld0))
}

// Ticks returns approximately `count` tick values. Faithful port of
// d3-scale's loggish.ticks(): walks powers of the base and the multiples
// 1..base-1 within each decade, falling back to linear ticks for large spans.
func (l *Log) Ticks(count int) []float64 {
	n := tickCount(count)
	u, v := l.domain[0], l.domain[1]
	r := v < u
	if r {
		u, v = v, u
	}
	i := l.logs(u)
	j := l.logs(v)
	base := l.base
	var z []float64
	if !(math.Mod(base, 1) == 0) || j-i >= float64(n) {
		// non-integer base or span too large: linear ticks in log-space
		span := j - i
		c := int(math.Min(span, float64(n)))
		if c < 1 {
			c = 1
		}
		z = ticksFloats(i, j, c)
		for k := range z {
			z[k] = l.pows(z[k])
		}
	} else {
		// integer base, small span: enumerate decade multiples
		ii := math.Floor(i)
		jj := math.Ceil(j)
		z = []float64{}
		if u > 0 {
			for ; ii <= jj; ii++ {
				for k := 1.0; k < base; k++ {
					t := k * l.pows(ii)
					if t < u {
						continue
					}
					if t > v {
						break
					}
					z = append(z, t)
				}
			}
		} else {
			// negative domain: walk from high to low
			for ; ii <= jj; ii++ {
				for k := base - 1; k >= 1; k-- {
					t := k * l.pows(ii)
					if t < u {
						continue
					}
					if t > v {
						break
					}
					z = append(z, t)
				}
			}
		}
		// d3: if z.length * 2 < n, fall back to linear ticks
		if len(z)*2 < n {
			z = ticksFloats(u, v, n)
		}
	}
	if r {
		for i2, j2 := 0, len(z)-1; i2 < j2; i2, j2 = i2+1, j2-1 {
			z[i2], z[j2] = z[j2], z[i2]
		}
	}
	return z
}

// Nice extends the domain to the nearest powers of the base.
func (l *Log) Nice(count int) *Log {
	d0, d1 := l.domain[0], l.domain[1]
	reverse := d1 < d0
	if reverse {
		d0, d1 = d1, d0
	}
	n0 := l.pows(math.Floor(l.logs(d0)))
	n1 := l.pows(math.Ceil(l.logs(d1)))
	if !reverse {
		l.domain = [2]float64{n0, n1}
	} else {
		l.domain = [2]float64{n1, n0}
	}
	l.rescale()
	return l
}

// Copy returns a deep copy.
func (l *Log) Copy() *Log {
	c := *l
	c.rebuildInterpolator()
	return &c
}

// rescale picks logs/pows based on base and domain sign, matching d3's
// loggish rescale().
func (l *Log) rescale() {
	l.negative = l.domain[0] < 0 || l.domain[1] < 0
	l.logs = logp(l.base)
	l.pows = powp(l.base)
	if l.negative {
		l.logs = reflectLog(l.logs)
		l.pows = reflectPow(l.pows)
	}
	l.rebuildInterpolator()
}

func (l *Log) rebuildInterpolator() {
	if l.round {
		l.interpolateFn = interpolateRound(l.rangeVals[0], l.rangeVals[1])
	} else {
		l.interpolateFn = interpolateNumber(l.rangeVals[0], l.rangeVals[1])
	}
}

// clampLogDomain clamps x to the domain's min/max (used when clamp is on).
func clampLogDomain(x float64, domain [2]float64) float64 {
	lo, hi := domain[0], domain[1]
	if hi < lo {
		lo, hi = hi, lo
	}
	if x < lo {
		return lo
	}
	if x > hi {
		return hi
	}
	return x
}

// logp returns the log function for a given base (d3's logp).
func logp(base float64) func(float64) float64 {
	if base == math.E {
		return math.Log
	}
	if base == 10 {
		return math.Log10
	}
	if base == 2 {
		return math.Log2
	}
	lb := math.Log(base)
	return func(x float64) float64 { return math.Log(x) / lb }
}

// powp returns the pow function for a given base (d3's powp).
func powp(base float64) func(float64) float64 {
	if base == 10 {
		return pow10
	}
	if base == math.E {
		return math.Exp
	}
	return func(x float64) float64 { return math.Pow(base, x) }
}

// pow10 mirrors d3's pow10: 1e+x, handling non-finite.
func pow10(x float64) float64 {
	if math.IsInf(x, 0) {
		if x < 0 {
			return 0
		}
		return x
	}
	return math.Pow(10, x)
}

// reflectLog returns -f(-x) (d3's reflect for logs on negative domains).
func reflectLog(f func(float64) float64) func(float64) float64 {
	return func(x float64) float64 { return -f(-x) }
}

// reflectPow returns -f(-x) (d3's reflect for pows on negative domains).
func reflectPow(f func(float64) float64) func(float64) float64 {
	return func(x float64) float64 { return -f(-x) }
}
